### PR TITLE
[app][feat] populate metsHdr section

### PR DESCRIPTION
**Pull request by M3ssman**
Hello,

as an user I really like your OOP-approach with METS/MODS.
Now I'd like to contribute some additional functionality regarding `metsHdr`-section that I do require for working with the `mets-model`-library in the context of mass-digitalization at the ULB. It consists of several extensions to the `metsHdr`-section that were lacking. This forced me to implement some rather hacky stuff to get around this limitation but I guess the proper way is to have these functionalities included in your nice library itself. 

I needed to alter the existing `metsHdr` date handling, since I did get it to work properly at de-serialization with the previous `Instant`-types. Maybe you can come up with a better idea to handle this I'm looking forward!

Unfortunately it can't be merged out of the box since it is based on the latest published version (tag 2.0), which is not the one the master is even with.

### CODE REVIEW

**Comment by yagee-de** [comment]
Thanks, for the contribution. Could you please check and resolve the conflicts?

**Comment by M3ssman** [comment]
I tried to use the `mycore-parent`-project revision which this project is currently pointing to. 
Not sure why codacy is not happy. When I run `mvn clean test` I get all lights green on the local side, though.

**Comment by M3ssman** [comment]
Ah well, I guess they suffer from a non-resolvable parent-POM `snapshot-44`, which is the base for this project's POM. 
Maybe I should update the Snapshot to the ~latest~ official parent-POM. Regarding to `search.maven.org` it's ~V45~ V44 ... ?

**Comment by rsteph-de** [comment]
> 
> Ah well, I guess they suffer from a non-resolvable parent-POM `snapshot-44`, which is the base for this project's POM.
> Maybe I should update the Snapshot to the ~latest~ official parent-POM. Regarding to `search.maven.org` it's ~V45~ V44 ... ?

You are right! Go with the latest released version:
https://mvnrepository.com/artifact/org.mycore/mycore-parent/45

**Comment by M3ssman** [comment]
@yagee-de It's been quite hard to please your travis. 
Never heard of this forbiddenapis stuff before. Is this part of your regular build process? 
Codacy still fails. Maybe PR-branch is not part of the usual review process.

**Comment by M3ssman** [comment]
@rsteph-de @yagee-de 
If there's still something missing, please let me know ... I really like to see any advances regarding this issue, since there will be some more based on this state

**Pull request merged**
